### ISSUE TITLE
Deprecated: Use of BaseTemplate::getFooterIcons was deprecated in MediaWiki 1.35

### ISSUE THREAD

**Issue by jdlrobson** [femiwiki/FemiwikiSkin#294] opened 2021-07-30 03:28 UTC
Seen on https://skins-demo.wmflabs.org/w/index.php?useskin=femiwiki
```
( ! ) Deprecated: Use of BaseTemplate::getFooterIcons was deprecated in MediaWiki 1.35. [Called from BaseTemplate::getFooter in /vagrant/mediawiki/includes/skins/BaseTemplate.php at line 363] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 376
Call Stack
#TimeMemoryFunctionLocation
10.0002397880{main}(  ).../index.php:0
20.0013403680require( '/vagrant/mediawiki/index.php' ).../index.php:5
30.15465370000wfIndexMain(  ).../index.php:46
40.15475372128MediaWiki->run(  ).../index.php:53
50.15515372384MediaWiki->main(  ).../MediaWiki.php:559
60.44837245800MediaWiki::{closure:/vagrant/mediawiki/includes/MediaWiki.php:937-943}(  ).../MediaWiki.php:952
70.44837245800OutputPage->output(  ).../MediaWiki.php:939
80.48577417280SkinFemiwiki->outputPage(  ).../OutputPage.php:2644
90.48597418352SkinFemiwiki->generateHTML(  ).../SkinTemplate.php:147
100.85639406344FemiwikiTemplate->execute(  ).../SkinTemplate.php:132
111.14419497824FemiwikiTemplate->getFooter(  ).../FemiwikiTemplate.php:99
121.14419497824FemiwikiTemplate->getFooterIcons(  ).../BaseTemplate.php:363
131.14419497824wfDeprecated(  ).../BaseTemplate.php:330
141.14419497824MWDebug::deprecated(  ).../GlobalFunctions.php:998
151.14419497920MWDebug::deprecatedMsg(  ).../MWDebug.php:230
161.14429499040MWDebug::sendRawDeprecated(  ).../MWDebug.php:352
171.14429499040trigger_error
(  ).../MWDebug.php:376
```

**Comment by lens0021** [comment] 2021-07-30 10:18
The call of the method was removed in #239 which has been merged on Jun 6 and included in [v1.7.1](https://github.com/femiwiki/FemiwikiSkin/releases/tag/v1.7.1). It seems the wiki uses the old version(97f1de2) prior to the [Special:Version](https://skins-demo.wmflabs.org/wiki/Special:Version?useskin=vector#mw-version-ext-skin-Femiwiki).

Would you contact the administrator of the wiki? @jdlrobson

**Comment by jdlrobson** [comment] 2021-07-30 12:58
I'll take a look today. Thanks !

**Comment by lens0021** [comment] 2021-09-18 11:34
It seems the link does not show the error message. Feel free to reopen this issue if the problem is still there.

**Closed by lens0021** 2021-09-18 11:34 UTC
Labels: deprecation
